#ROUTE FOR FILMS
index:
    path: /
    controller: App\Controller\FilmController::listFilms
  
index-list-film:
    path: /film/{filmx}
    controller: App\Controller\FilmController::afficheFilm

#ROUTE FOR MEMBERS
shows-all-members:
    path: /members
    controller: App\Controller\MemberController::showAllMembers

shows-member:
    path: /members/{id}
    controller: App\Controller\MemberController::showMember

